### ISSUE TITLE
This packages gives unexpected results when given non-ASCII characters

### ISSUE THREAD

**Issue by Eggbertx** [aquilax/tripcode#6]
For example, it treats "ññññ" like an empty string and panics when given "糯ｫT弓(窶" (when it should return Pants.f1Fk)

**Comment by aquilax** [comment]
Thanks for the feedback @Eggbertx .The second case was a bug in the seed calculation.
The first one seems to be expected behaviour, at least in this implementation https://github.com/KenanY/tripcode 
`japanese.ShiftJIS` returns empty buffer with that input.

**Comment by Eggbertx** [comment]
Awesome! Looking around, I've noticed that support seems to be inconsistent with ñ and other non-ASCII, non-Japanese characters, but considering traditional tripcode generation uses Shift-JIS, a Japanese encoding, that shouldn't be too surprising.
